FROM almalinux:9
ARG course="Devops with AWS" \
    duration="120hrs"
ENV course1="Devops with AWS" \
    duration1="120hrs"
RUN echo "course: $course, duration: $duration"
RUN echo "course: $course1, duration: $duration1"
CMD [ "sleep", "100" ]